[package]
name = "graphql-walker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql-tools = "0.0.19"

[dev-dependencies]
insta = "1.14.0"
